### ISSUE TITLE
Function missing in ChiCMaxima_Caller.r

### ISSUE THREAD

**Issue by stefanucci-luca** [yousra291987/ChiCMaxima#2]
Dear Yousra,

I was carrying on with the ChiCMaxima_Caller.r, following the instrunction on the github page. I tried the test data:

```Rscript ChiCMaxima_Caller.r -i mESrep1_chr15.ibed -o proof_mESrep1 -w 20``` and 
```Rscript ChiCMaxima_Caller.r -i mESrep2_chr15.ibed -o proof_mESrep2 -w 20```.

I am getting this error message for both of them:
```
No bait to bait interactions in ibed
All cis interactions in ibed
Error in .Internal(sorted_fpass(x, decreasing, na.last)) : 
  there is no .Internal function 'sorted_fpass'
Calls: order -> standardGeneric -> eval -> eval -> eval -> order
Execution halted
```

Same error message with my data. Do you have any idea how to sort this out?
Do you want me to close this issue as solved and open a new one?

Thank you,
Luca

**Comment by stefanucci-luca** [comment]
Hi Yousra, 

I've updated R version from 3.3 to 3.5.0 and all the dependencies and the script is now working, but the output of ```Rscript ChiCMaxima_Caller.r -i mESrep1_chr15.ibed -o proof_mESrep1 -w 20``` doesn't have a 12th column. 

e.g
```
ID_Bait	chr_Bait	start_Bait	end_Bait	Bait_name	ID_OE	chr_OE	start_OE	end_OE	OE_name	N
632044	chr15	8994505	9004855	1110020G09Rik	631804	chr15	8266618	8270171	.	6
632044	chr15	8994505	9004855	1110020G09Rik	631899	chr15	8587922	8593162	.	10
632044	chr15	8994505	9004855	1110020G09Rik	632046	chr15	9006479	9007880	.	48
632044	chr15	8994505	9004855	1110020G09Rik	632179	chr15	9373995	9375303	.	6
632044	chr15	8994505	9004855	1110020G09Rik	632473	chr15	10185037	10189390	.	5
654588	chr15	76776716	76781543	1110038F14Rik	654485	chr15	76369825	76378307	.	4
654588	chr15	76776716	76781543	1110038F14Rik	654590	chr15	76788212	76788422	.	23
657946	chr15	88919453	88923076	1300018J18Rik	657905	chr15	88761254	88765726	.	8
657946	chr15	88919453	88923076	1300018J18Rik	657944	chr15	88906836	88907380	.	11
```


 
```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Scientific Linux 7.6 (Nitrogen)

locale:
 [1] LC_CTYPE=en_GB.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_GB.UTF-8        LC_COLLATE=en_GB.UTF-8    
 [5] LC_MONETARY=en_GB.UTF-8    LC_MESSAGES=en_GB.UTF-8   
 [7] LC_PAPER=en_GB.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_GB.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] parallel  stats4    stats     graphics  grDevices utils     datasets 
[8] methods   base     

other attached packages:
[1] psych_1.8.12         zoo_1.8-6            data.table_1.12.2   
[4] MASS_7.3-51.4        GenomicRanges_1.34.0 GenomeInfoDb_1.18.2 
[7] IRanges_2.16.0       S4Vectors_0.20.1     BiocGenerics_0.28.0 

loaded via a namespace (and not attached):
 [1] lattice_0.20-38        bitops_1.0-6           grid_3.5.0            
 [4] nlme_3.1-137           zlibbioc_1.28.0        XVector_0.22.0        
 [7] tools_3.5.0            foreign_0.8-71         RCurl_1.95-4.12       
[10] compiler_3.5.0         mnormt_1.5-5           GenomeInfoDbData_1.2.0
```
Hope this help. 
Thanks for your support.
Luca

**Comment by yousra291987** [comment]
Hi Luca,
  The output of ChiCMaxima_Caller is supposed to be an 11-column format. Originally, we had a 12th column to indicate some form of fold-change over the expected background, but this has now been deprecated as it was not actually useful. Please indicate where you read that you should expect 12 columns and I will update the information accordingly.
Best,

**Comment by stefanucci-luca** [comment]
Hi Yousra,

Thanks for your answer.

In the README.md, USAGE section, point 1/ ChiCMaxima_Caller.
> [...]
> Outputs:
> . output_interactions.ibed. The called interactions, in the same ibed format as the input, **with a twelfth column, Enrichment - log2(local maximum score/fitted cis-decay score).**

So, I assume that all the interactions in the output.ibed are the maximum of the window I've set? 

Best
Luca

**Comment by yousra291987** [comment]
Hi Luca,

Yes, all reported interactions are the local maximum of the window that you have set.

Best,

Yousra
