### ISSUE TITLE
locked binding 

### ISSUE THREAD

**Issue by MigleMi** [yousra291987/ChiCMaxima#3]
Hello, 

I am trying ChiCBrowser with test data and I come with this issue:
Error in select <<- tktoplevel() : 
  cannot change value of locked binding for 'select'

Could you please help me to solve this issue? I am using the latest R version 3.6.1, could this be the problem?

**Comment by yousra291987** [comment]
Hi, 

I just updated the ChiCBrowser. Could you please download the updated version and run it again!

Thank you,

**Comment by marina-yurieva** [comment]
Hi I downloaded ChiCMaxima recently but have the same issue with the test dataset. Is there a way to fix it?

Thank you!
