### ISSUE TITLE
ID_OE

### ISSUE THREAD

**Issue by MigleMi** [yousra291987/ChiCMaxima#4]
Hello again, 

I have an issue when I want to upload files to ChiCBrowser, when a table pops to manage replicates and conditions:  Error in set$entry[[i]] : subscript out of bounds 

I noticed that ChiCMaxima_MergeRep2.r script generates .ibed files without ID_OE column, however, when I upload single replicate ibed file with 11 columns it gives me the same error

Otherwise thank you for great work!

Best regards,
Migle

**Comment by yousra291987** [comment]
Hi,

Have you used ChiCMaxima_Collate.r  to generate the input file for the ChiCBrowser?

ChiCMaxima_MergeRep2.r  is used to merge ,only, interactions called as significant. If you want to visualize your data you should use the original input file (ibed) after using ChiCMaxima_Collate.r. 

I hope this will resolve your problem.


Best,

Yousra
