### ISSUE TITLE
Collate-error cannot open connection

### ISSUE THREAD

**Issue by jumoline** [yousra291987/ChiCMaxima#5]
Hi,
I get this error when I try:
(tried with the test data)
Rscript ChiCMaxima_Collate.r -k testdata/collate_key.txt -o testdata/testcollate.ibed

Error in file(file, "rt") : cannot open the connection
Calls: read.delim -> read.table -> file
Execution halted

I tried in both Linux (with all dependencies installed) and Win7 Rv3.6.1
any ideas for fixing this?
J

**Comment by yousra291987** [comment]
Hi,

This error is due to a wrong path to the file. If you want to run the test data you should be in the folder of ChiCmaxima, otherwise, you should give the whole path to the test data file. 

Yousra
