### ISSUE TITLE
sample without replicates

### ISSUE THREAD

**Issue by ivyhzau** [yousra291987/ChiCMaxima#9]
I have applied ChiCMaxima to call loops for cHi-C data. But I noticed that the samples in Readme at least have 2 replicates. I wonder whether it is also good for running the samples without other replicates? If yes, is there any further filtering step after finished running ChiCMaxima_Calle @yousra291987 @TomSexton00

**Comment by TomSexton00** [comment]
Hi. As mentioned in the paper, there is some difficulty with reproducibility between replicates with CHi-C data. You can certainly run ChiCMaxima_Caller with just one replicate (in fact, this tool can only be run on individual replicates; it is what is done afterwards which varies), but be careful not to overinterpret any results (whatever tool you use). Experimental validation and biological replicates are certainly desirable!
